DROP VIEW IF EXISTS refoulement_replaced_by_pu ping_reach;
DROP VIEW IF EXISTS process_maintenance_event;
DROP VIEW IF EXISTS vw_pumping_reach;
DROP VIEW IF EXISTS vw_last_inspection;
DROP VIEW IF EXISTS vw_last_cleaning;
DROP VIEW IF EXISTS vw_collecting_pipe_agg;
DROP VIEW IF EXISTS vw_batch_inspection_agg;
DROP VIEW IF EXISTS vw_batch_cleaning_agg;
DROP VIEW IF EXISTS vw_edit_main_pipe_name;
DROP VIEW IF EXISTS vw_edit_collecting_pipe;
